// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqzljyqvuqPmm4g85tvbZnRCspAjystQ0',
    appId: '1:238822129023:web:b438efba6affa7292a6e4a',
    messagingSenderId: '238822129023',
    projectId: 'evently-3f690',
    authDomain: 'evently-3f690.firebaseapp.com',
    storageBucket: 'evently-3f690.firebasestorage.app',
    measurementId: 'G-FH84E6Z4D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl0__w8TOt-rqJk8nDFriA7S2hCI-Viis',
    appId: '1:238822129023:android:ad7a244b972c04072a6e4a',
    messagingSenderId: '238822129023',
    projectId: 'evently-3f690',
    storageBucket: 'evently-3f690.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuivgqDQu9ecpJ4lzwROiagC1Y82bOmas',
    appId: '1:238822129023:ios:3fb0ba9b6aa828872a6e4a',
    messagingSenderId: '238822129023',
    projectId: 'evently-3f690',
    storageBucket: 'evently-3f690.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuivgqDQu9ecpJ4lzwROiagC1Y82bOmas',
    appId: '1:238822129023:ios:3fb0ba9b6aa828872a6e4a',
    messagingSenderId: '238822129023',
    projectId: 'evently-3f690',
    storageBucket: 'evently-3f690.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqzljyqvuqPmm4g85tvbZnRCspAjystQ0',
    appId: '1:238822129023:web:b438efba6affa7292a6e4a',
    messagingSenderId: '238822129023',
    projectId: 'evently-3f690',
    authDomain: 'evently-3f690.firebaseapp.com',
    storageBucket: 'evently-3f690.firebasestorage.app',
    measurementId: 'G-FH84E6Z4D5',
  );

}